swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transact:
      get:
        tags:
          - Transact Module
        summary: Transact
        description: API for load Transact
        parameters:
          - in: header
            name: Authorization
            description: Attach Bearer JWT token
            required: true
        produces:
          - application/json
        responses:
          '200':
            description: Transacts has been load Successfully
            schema:
              $ref: '#/definitions/TransactResponse'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
      post:
        security:
          - Bearer: []
        tags:
          - Transact Module
        summary: Transact Detail API
        description: API for create a transaction
        parameters:
          - in: header
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - in: body
            name: body
            description: Transact Payload
            required: true
            schema:
              $ref: '#/definitions/TransactCreate'
        produces:
          - application/json
        responses:
          '200':
            description: Transaction detail retrieved successully
            schema:
              $ref: '#/definitions/TransactDetail'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
  /transact/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transact Module
      summary: Transact Detail API
      description: API for fetching a transaction detail
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction detail retrieved successully
          schema:
            $ref: '#/definitions/TransactDetail'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error    
    put:
      security:
        - Bearer: []
      tags:
        - Transact Module
      summary: Transact Detail API
      description: API for editing a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update transaction detail attributes
          required: true
          schema:
            $ref: '#/definitions/TransactCreate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction has been editing successully
          schema:
            $ref: '#/definitions/TransactDetailAPIResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transact Module
      summary: Transact Detail API
      description: API for deleting a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction has been delete successully
          schema:
            $ref: '#/definitions/TransactDetailDeleteResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transact:
    properties:
      id: 
        type: string
        description: Transact id
      status:
        type: string
        description: Transact status code
      description: 
        type: string
        description: Transact description
      amount: 
        type: number
        description: Transact amount
      balance: 
        type: number
        description: Transact balance
      date: 
        type: string
        description: Transact date
  TransactResponse:
    type: array
    items:
        $ref: '#/definitions/TransactDetail'
  TransactCreate:
    properties:
      status:
        type: string
        description: Transact status code
      description: 
        type: string
        description: Transact description
      amount: 
        type: number
        description: Transact amount
      balance: 
        type: number
        description: Transact balance
  TransactDetail:
    properties:
      id: 
        type: string
        description: Transact id
      status:
        type: string
        description: Transact status code
      description: 
        type: string
        description: Transact description
      amount: 
        type: number
        description: Transact amount
      balance: 
        type: number
        description: Transact balance
      date: 
        type: string
        description: Transact date
  TransactDetailResponse:
    type: object
    properties:
      id:
        type: string
  TransactDetailAPIResponse:
    type: object
    properties:
      message:
        type: string
  TransactDetailDelete:
    type: object
    properties:
      id:
        type: string
  TransactDetailDeleteResponse:
    type: object
    properties:
      message:
        type: string