swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /Transaction:
      get:
        tags:
          - Transaction Module
        summary: Transaction
        description: API for load Transaction
        parameters:
          - in: header
            name: Authorization
            description: Attach Bearer JWT token
            required: true
        produces:
          - application/json
        responses:
          '200':
            description: Transactions has been load Successfully
            schema:
              $ref: '#/definitions/TransactionResponse'
          '500':
            description: Internal Server Error
      post:
        security:
          - Bearer: []
        tags:
          - Transaction Module
        summary: Transaction Detail API
        description: API for create a Transaction
        parameters:
          - in: header
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - in: body
            name: body
            description: Transaction Payload
            required: true
            schema:
              $ref: '#/definitions/TransactionCreate'
        produces:
          - application/json
        responses:
          '200':
            description: Transaction detail retrieved successully
            schema:
              $ref: '#/definitions/TransactionDetail'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
  /Transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction Detail API
      description: API for fetching a Transaction detail
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction detail retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '500':
          description: Internal Server Error    
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction Detail API
      description: API for editing a Transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update Transaction detail attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionCreate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction has been editing successully
          schema:
            $ref: '#/definitions/TransactionDetailAPIResponse'            
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction Detail API
      description: API for deleting a Transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction has been delete successully
          schema:
            $ref: '#/definitions/TransactionDetailDeleteResponse'
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    properties:
      id: 
        type: string
        description: Transaction id
      status:
        type: string
        description: Transaction status code
      description: 
        type: string
        description: Transaction description
      amount: 
        type: number
        description: Transaction amount
      balance: 
        type: number
        description: Transaction balance
      date: 
        type: string
        description: Transaction date
  TransactionResponse:
    type: array
    items:
        $ref: '#/definitions/TransactionDetail'
  TransactionCreate:
    properties:
      status:
        type: string
        description: Transaction status code
      description: 
        type: string
        description: Transaction description
      amount: 
        type: number
        description: Transaction amount
      balance: 
        type: number
        description: Transaction balance
  TransactionDetail:
    properties:
      id: 
        type: string
        description: Transaction id
      status:
        type: string
        description: Transaction status code
      description: 
        type: string
        description: Transaction description
      amount: 
        type: number
        description: Transaction amount
      balance: 
        type: number
        description: Transaction balance
      date: 
        type: string
        description: Transaction date
  TransactionDetailResponse:
    type: object
    properties:
      id:
        type: string
  TransactionDetailAPIResponse:
    type: object
    properties:
      message:
        type: string
  TransactionDetailDelete:
    type: object
    properties:
      id:
        type: string
  TransactionDetailDeleteResponse:
    type: object
    properties:
      message:
        type: string